# Traefik Plugin Manifest
displayName: GeoBlock Middleware
type: middleware

import: github.com/CangioUni/traefik-geoblock-plugin

summary: 'Middleware plugin to geoblock incoming connections based on IP address and country with local database support'

testData:
  allowedCountries:
    - IT
    - DE
  blockedCountries: []
  queryURL: https://ipapi.co/{ip}/json/
  databaseURL: ""
  databasePath: /tmp/ipinfo_lite.json
  cacheDuration: 60
  defaultAction: allow
  blockMessage: Access denied from your country
  blockPageTitle: Access Denied
  blockPageBody: ""
  redirectURL: ""
  logBlocked: true
  trustedProxies: []
